name: AE-D
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/cxr/sota/
#
# Experiment
#
experiment:
  name: MAD_Dummy
  task: train
  weights: #'./weights_cxr/AE-D/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.convolutional_autoencoders
  class_name: DenseConvAutoEncoderBaur
  params:
    in_channels: 1
    channels:
      - 32 # for 128x128 input
      - 64
      - 128
    strides:
      - 2 # for 128x128 input
      - 2
      - 2
      - 2
    out_ch: 1
    kernel_size: 5
    norm: batch
    act: leakyrelu
    deconv_mode: trans
#
# Trainer
#
trainer:
  module_name: projects.Autoencoders.Trainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 1000
    # Loss
    loss:
      module_name: optim.losses.ln_losses
      class_name: L1
      params:
    # Optimizer
    optimizer_params:
      lr: 5.0e-4
  # Data Loader
  data_loader:
# CXR
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.cxr_loader
          class_name: CXRDataset
        data_dir:
          train:
            - './data/CXR/splits/cxr_normal_train.csv'
          val:
            - './data/CXR/splits/cxr_normal_val.csv'
          test:
            - './data/CXR/splits/cxr_normal_test.csv'
        target_size: *target_size
        #        batch_size: 128 # orig
        batch_size: 64
# Downstream tasks
downstream_tasks:
  pneumonia:
    module_name: projects.Autoencoders.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          dataset_module:
            module_name: data.loaders.cxr_loader
            class_name: CXRDataset
          target_size: *target_size
          batch_size: *dbatch_size
      datasets:
        Normal_CXR:
          data_dir:
            test:
            - './data/CXR/splits/cxr_normal_test.csv'
        Pneumonia:
          data_dir:
            test:
  generalization:
    module_name: projects.Autoencoders.DownstreamEvaluator_exp
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          dataset_module:
            module_name: data.loaders.cxr_loader
            class_name: CXRDataset
          target_size: *target_size
          batch_size: *dbatch_size
      datasets:
        Normal_Padchest:
          data_dir:
            test:
              - './data/padchest/splits/normal_test.csv'
        Covid:
          data_dir:
            test:
              - './data/CXR/splits/cxr_covid_padchest_test.csv'